# Generated by Django 3.2.10 on 2022-11-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_report', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseasereportmodel',
            old_name='diisease_report_id',
            new_name='disease_report_id',
        ),
        migrations.AddField(
            model_name='diseasereportmodel',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
