# Generated by Django 3.2.10 on 2022-11-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_report', '0002_auto_20221102_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasereportmodel',
            name='death_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='diseasereportmodel',
            name='discharge_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='diseasereportmodel',
            name='new_case_count',
            field=models.IntegerField(default=0),
        ),
    ]
