# Generated by Django 3.2.10 on 2022-11-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_report', '0003_auto_20221102_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasereportmodel',
            name='location',
            field=models.CharField(default='0,0', max_length=100),
        ),
    ]
