# Generated by Django 3.2 on 2023-01-01 14:46

from django.db import migrations, models
from dbview.helpers import CreateView

class Migration(migrations.Migration):

    dependencies = [
        ('disease_report', '0004_alter_diseasereportmodel_location'),
    ]

    operations = [
        CreateView(
            name='view_hospital_d',
            fields=[
                ('disease_report_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
