# Generated by Django 3.2 on 2023-01-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_report', '0005_view_hospital_d'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('disease_report_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'disease_report_view_hospital_d',
                'managed': False,
            },
        ),
    ]
