# Generated by Django 3.2 on 2023-01-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_report', '0006_tempuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseReportGeneralSummary',
            fields=[
                ('disease_report_id', models.AutoField(primary_key=True, serialize=False)),
                ('disease_type_id', models.IntegerField()),
                ('death_count', models.IntegerField()),
                ('new_case_count', models.IntegerField()),
                ('discharge_count', models.IntegerField()),
                ('created_day', models.DateField()),
            ],
            options={
                'db_table': 'view_disease_summary',
                'managed': False,
            },
        ),
    ]
