# Generated by Django 3.2 on 2023-01-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_report', '0007_diseasereportgeneralsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictDiseaseReportSummary',
            fields=[
                ('disease_report_id', models.AutoField(primary_key=True, serialize=False)),
                ('disease_type_id', models.IntegerField()),
                ('district_name', models.CharField(max_length=255)),
                ('district_id', models.IntegerField()),
                ('death_count', models.IntegerField()),
                ('new_case_count', models.IntegerField()),
                ('discharge_count', models.IntegerField()),
                ('created_day', models.DateField()),
            ],
            options={
                'db_table': 'view_districts_data',
                'managed': False,
            },
        ),
    ]
