# Generated by Django 3.2 on 2023-01-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_report', '0009_hospitaldiseasereportsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalBasedDiseaseReport',
            fields=[
                ('disease_report_id', models.AutoField(primary_key=True, serialize=False)),
                ('disease_type_id', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('district_name', models.CharField(max_length=255)),
                ('district_id', models.IntegerField()),
                ('hospital_name', models.CharField(max_length=255)),
                ('hospital_id', models.IntegerField()),
                ('death_count', models.IntegerField()),
                ('new_case_count', models.IntegerField()),
                ('discharge_count', models.IntegerField()),
                ('created_day', models.DateField()),
            ],
            options={
                'db_table': 'view_general_disease_report',
                'managed': False,
            },
        ),
    ]
