# Generated by Django 3.2.10 on 2022-11-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseTypesModel',
            fields=[
                ('disease_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('disease_type_name', models.CharField(max_length=100)),
                ('disease_type_desc', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Disease Types',
            },
        ),
    ]
