# Generated by Django 3.2.10 on 2022-11-02 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictModel',
            fields=[
                ('district_id', models.AutoField(primary_key=True, serialize=False)),
                ('district_name', models.CharField(max_length=100, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Hospitals',
            },
        ),
        migrations.CreateModel(
            name='HospitalsModel',
            fields=[
                ('hospital_id', models.AutoField(primary_key=True, serialize=False)),
                ('hospital_name', models.CharField(max_length=100)),
                ('assigned_number', models.IntegerField(max_length=12, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.districtmodel')),
            ],
            options={
                'verbose_name_plural': 'Hospitals',
            },
        ),
    ]
