# Generated by Django 3.2.10 on 2022-11-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalsmodel',
            name='assigned_number',
            field=models.IntegerField(unique=True),
        ),
    ]
